version: "3.5"

services:
  api01: &api
    build:
      context: ../../
      dockerfile: ./eng/docker/dockerfile
      args:
        - PUBLISH_FOLDER=app/
    hostname: api01
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:3000      
      - ConnectionStrings__Database=Server=db;Port=5432;Database=RinhaBackend;User Id=postgres;Password=123;Pooling=true;MinPoolSize=240;MaxPoolSize=490;ConnectionLifeTime=15;Auto Prepare Min Usages=1;No Reset On Close=true;
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - "3001:3000"
    depends_on:
      - db
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "80MB"

  api02:
    <<: *api
    hostname: api02
    # environment:
    #  - ASPNETCORE_URLS=http://0.0.0.0:3000      
    #   - ConnectionStrings__Default=Server=db;Port=5432;Database=RinhaBackend;User Id=postgres;Password=123;
    ports:
      - "3002:3000"
  
  api03:
    <<: *api
    hostname: api02
    # environment:
    #  - ASPNETCORE_URLS=http://0.0.0.0:3000      
    #   - ConnectionStrings__Default=Server=db;Port=5432;Database=RinhaBackend;User Id=postgres;Password=123;
    ports:
      - "3003:3000"

  api04:
    <<: *api
    hostname: api02
    # environment:
    #  - ASPNETCORE_URLS=http://0.0.0.0:3000      
    #   - ConnectionStrings__Default=Server=db;Port=5432;Database=RinhaBackend;User Id=postgres;Password=123;
    ports:
      - "3004:3000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - api03
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "134MB"
    ulimits:
      nofile:
        soft: 500000
        hard: 500000
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=RinhaBackend
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    # deploy:
      # resources:
        # limits:
    #       cpus: "0.5"
          # memory: "256MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1